[package]
name = "optimization"
version = "0.1.0"
authors = ["Jiří Sejkora <sejsel@sejsel.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
itertools = "0.10.0"